### ISSUE TITLE
Trying to compile on OS X 10.9

### ISSUE THREAD

**Issue by seanleblanc** [jonklein/breve#1]
Hello, I'm trying to compile this on OS X 10.9

I cloned the git repo and then ran autoconf to get a configure script. Running that, I found I still hadn't installed gls and ode and did so with brew install gsl and brew install ode.

Then, I had many errors similar to the following:

1 error generated.
Generating dependencies for simulation/worldObject.cc
In file included from simulation/worldObject.cc:2:
In file included from include/breve/worldObject.h:5:
In file included from include/breve/shape.h:25:
In file included from /usr/local/include/ode/ode.h:30:
/usr/local/include/ode/common.h:59:2: error: You can only #define dSINGLE or dDOUBLE, not both.
# error You can only #define dSINGLE or dDOUBLE, not both.

Just as an experiment, since I see it's trying to set -DdDOUBLE on commandline, instead of #error, I #undef SINGLE.

Now, it complains about QT:

c++  -I..  -c -o QTInstrumentFunctions.o QTInstrumentFunctions.cc
QTInstrumentFunctions.cc:29:2: error: unknown type name 'NoteAllocator'; did you mean '__CFAllocator'?
        NoteAllocator allocator;
        ^~~~~~~~~~~~~
        __CFAllocator
/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:411:22: note: '__CFAllocator' declared here
typedef const struct __CFAllocator \* CFAllocatorRef;
                     ^
QTInstrumentFunctions.cc:29:16: error: field has incomplete type '__CFAllocator'
        NoteAllocator allocator;
                      ^
/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:411:22: note: forward declaration of '__CFAllocator'
typedef const struct __CFAllocator \* CFAllocatorRef;
                     ^
QTInstrumentFunctions.cc:30:2: error: unknown type name 'NoteChannel'
        NoteChannel channel;
        ^
QTInstrumentFunctions.cc:31:2: error: unknown type name 'NoteRequest'
        NoteRequest request;
        ^
QTInstrumentFunctions.cc:39:2: error: unknown type name 'NoteRequest'
        NoteRequest request;
        ^
QTInstrumentFunctions.cc:45:17: warning: 'OpenDefaultComponent' is deprecated: first deprecated in OS X 10.8 [-Wdeprecated-declarations]
        i->allocator = OpenDefaultComponent( 'nota', 0 );
                       ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Components.h:1004:1: note: 'OpenDefaultComponent' has been explicitly
      marked deprecated here
OpenDefaultComponent(
^
1 warning and 5 errors generated.
make[2]: **\* [QTInstrumentFunctions.o] Error 1
make[1]: [all] Error 2 (ignored)

I guess I should ask - is compiling under 10.9 expected to work? I see there are commits related to making it work, so thought I'd try. The current screensaver binary on the website won't run for me, so was having a go a compiling it myself.

Cheers,
Sean
